-- Differentiator descriptions, from the STG front-end export in
-- docs/foundationExports. Generated - do not hand-edit.
--
-- The tenant's foundation/diffid feed is empty on STG, so master_pkg harvests diff
-- IDs from the item feed and gets codes with no descriptions. A colour dropdown
-- showing "08610" is not usable; this fills in "BLACK CHUTNEY SAIL ANIMAL".
--
-- Only the diffs already present in MASTER_DATA are updated - the export carries
-- 48,837 and almost none of them are in use here.
--
--   deploy/mdutils/sql.sh deploy/mdutils/seed_diff_descriptions.sql

set define off

update master_data set description = 'BLACK' where data_type = 'DIFF_C' and data_code = '00000' and parent_code = '~';
update master_data set description = 'BLACK LEATHER' where data_type = 'DIFF_C' and data_code = '00078' and parent_code = '~';
update master_data set description = 'BLACK SUEDE' where data_type = 'DIFF_C' and data_code = '00079' and parent_code = '~';
update master_data set description = 'BLACK CANVAS' where data_type = 'DIFF_C' and data_code = '00347' and parent_code = '~';
update master_data set description = 'BLACK WHITE' where data_type = 'DIFF_C' and data_code = '01158' and parent_code = '~';
update master_data set description = 'BLACK GUM' where data_type = 'DIFF_C' and data_code = '01333' and parent_code = '~';
update master_data set description = 'BLACK EVA' where data_type = 'DIFF_C' and data_code = '02269' and parent_code = '~';
update master_data set description = 'SUEDE BLACK' where data_type = 'DIFF_C' and data_code = '02975' and parent_code = '~';
update master_data set description = 'ORIGIN STORY EGRET BLACK' where data_type = 'DIFF_C' and data_code = '03659' and parent_code = '~';
update master_data set description = 'BLACK BLUE' where data_type = 'DIFF_C' and data_code = '03859' and parent_code = '~';
update master_data set description = 'OILED BLACK LEATHER' where data_type = 'DIFF_C' and data_code = '04102' and parent_code = '~';
update master_data set description = 'CORE BLACK' where data_type = 'DIFF_C' and data_code = '04246' and parent_code = '~';
update master_data set description = 'MIDNIGHT' where data_type = 'DIFF_C' and data_code = '04415' and parent_code = '~';
update master_data set description = 'FOSSILIZED EGRET BLACK' where data_type = 'DIFF_C' and data_code = '04750' and parent_code = '~';
update master_data set description = 'TRIPLE BLACK' where data_type = 'DIFF_C' and data_code = '04988' and parent_code = '~';
update master_data set description = 'CORE BLACK WHITE CORE BLACK' where data_type = 'DIFF_C' and data_code = '05271' and parent_code = '~';
update master_data set description = 'BASALT' where data_type = 'DIFF_C' and data_code = '07372' and parent_code = '~';
update master_data set description = 'NATURAL BLACK EGRET' where data_type = 'DIFF_C' and data_code = '07665' and parent_code = '~';
update master_data set description = 'BLACK BLACK SMOKE GREY VAST GREY' where data_type = 'DIFF_C' and data_code = '08010' and parent_code = '~';
update master_data set description = 'BLACK CHUTNEY SAIL ANIMAL' where data_type = 'DIFF_C' and data_code = '08610' and parent_code = '~';
update master_data set description = 'SUEDE BLACK WHITE GUM BROWN TOTAL ORANGE' where data_type = 'DIFF_C' and data_code = '08621' and parent_code = '~';
update master_data set description = 'BLACK BLACK METALLIC SILVER WHITE' where data_type = 'DIFF_C' and data_code = '08630' and parent_code = '~';
update master_data set description = 'BLACK WHITE POLKA DOT' where data_type = 'DIFF_C' and data_code = '08857' and parent_code = '~';
update master_data set description = 'EGRET BRIGHT POPPY EMBROIDERED FLOWERS BLACK' where data_type = 'DIFF_C' and data_code = '08908' and parent_code = '~';
update master_data set description = 'MIDNIGHT SUEDE OILED LEATHER' where data_type = 'DIFF_C' and data_code = '08932' and parent_code = '~';
update master_data set description = 'EARTHY VEGAN BLACK' where data_type = 'DIFF_C' and data_code = '08949' and parent_code = '~';
update master_data set description = 'DARK MOSS EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09090' and parent_code = '~';
update master_data set description = 'DEEP WATERS EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09580' and parent_code = '~';
update master_data set description = 'UTILITY EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09581' and parent_code = '~';
update master_data set description = 'PAPYRUS EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09590' and parent_code = '~';
update master_data set description = 'DESERT BUCK BLACK' where data_type = 'DIFF_C' and data_code = '09742' and parent_code = '~';
update master_data set description = 'SQUIRREL EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09817' and parent_code = '~';
update master_data set description = 'EGRET EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09885' and parent_code = '~';
update master_data set description = 'WHITE BLACK SPLIT' where data_type = 'DIFF_C' and data_code = '09943' and parent_code = '~';
update master_data set description = 'UNCHARTED WATERS EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09945' and parent_code = '~';
update master_data set description = 'DUNESCAPE EGRET BLACK' where data_type = 'DIFF_C' and data_code = '09946' and parent_code = '~';
update master_data set description = 'WHITE' where data_type = 'DIFF_C' and data_code = '10000' and parent_code = '~';
update master_data set description = 'WHITE BLACK' where data_type = 'DIFF_C' and data_code = '10508' and parent_code = '~';
update master_data set description = 'WHITE EVA' where data_type = 'DIFF_C' and data_code = '11132' and parent_code = '~';
update master_data set description = 'OFF WHITE WHITE' where data_type = 'DIFF_C' and data_code = '12832' and parent_code = '~';
update master_data set description = 'WHITE OFF WHITE' where data_type = 'DIFF_C' and data_code = '12872' and parent_code = '~';
update master_data set description = 'WHITE VAST GREY DARK GREY' where data_type = 'DIFF_C' and data_code = '14297' and parent_code = '~';
update master_data set description = 'WHITE MULTI WHITE' where data_type = 'DIFF_C' and data_code = '14619' and parent_code = '~';
update master_data set description = 'WHITE RACER BLUE SAIL' where data_type = 'DIFF_C' and data_code = '14777' and parent_code = '~';
update master_data set description = 'THUNDERSTORM PURE PLATINUM SAIL' where data_type = 'DIFF_C' and data_code = '14798' and parent_code = '~';
update master_data set description = 'WHITE BLACK SAIL' where data_type = 'DIFF_C' and data_code = '15511' and parent_code = '~';
update master_data set description = 'WILD PINE WHITE EXCLUSIVE' where data_type = 'DIFF_C' and data_code = '15663' and parent_code = '~';
update master_data set description = 'SUMMIT WHITE BLACK PALE IVORY BEACH WHITE' where data_type = 'DIFF_C' and data_code = '15703' and parent_code = '~';
update master_data set description = 'WHITE WHITE LEOPARD' where data_type = 'DIFF_C' and data_code = '15711' and parent_code = '~';
update master_data set description = 'WHITE YELLOW TINT ICEY PINK WHITE' where data_type = 'DIFF_C' and data_code = '16041' and parent_code = '~';
update master_data set description = 'WHITE NEON YELLOW MAGENTA BLACK' where data_type = 'DIFF_C' and data_code = '16150' and parent_code = '~';
update master_data set description = 'NEXT NATURE SAIL WHITE' where data_type = 'DIFF_C' and data_code = '16323' and parent_code = '~';
update master_data set description = 'SUMMIT WHITE ATMOSPHERE FOSSIL STONE' where data_type = 'DIFF_C' and data_code = '16479' and parent_code = '~';
update master_data set description = 'SUMMIT WHITE LIHT MADDER ROOT FOSSIL STONE' where data_type = 'DIFF_C' and data_code = '16512' and parent_code = '~';
update master_data set description = 'WONDER WHITE' where data_type = 'DIFF_C' and data_code = '16582' and parent_code = '~';
update master_data set description = 'WHITE BARELY GREEN' where data_type = 'DIFF_C' and data_code = '16665' and parent_code = '~';
update master_data set description = 'WHITE DARK MOCHA ATMOSPHERE SAIL' where data_type = 'DIFF_C' and data_code = '16714' and parent_code = '~';
update master_data set description = 'GOLF WANG VINTAGE WHITE BLUE TOPAZ' where data_type = 'DIFF_C' and data_code = '16752' and parent_code = '~';
update master_data set description = 'WHITE WHITE WHITE WHITE' where data_type = 'DIFF_C' and data_code = '16900' and parent_code = '~';
update master_data set description = 'SUMMIT WHITE HOT CURRY MARS STONE' where data_type = 'DIFF_C' and data_code = '16906' and parent_code = '~';
update master_data set description = 'WONDER STEEL OF WHITE' where data_type = 'DIFF_C' and data_code = '16983' and parent_code = '~';
update master_data set description = 'WHITE METALLIC SILVER SAIL SUMMIT WHITE' where data_type = 'DIFF_C' and data_code = '17072' and parent_code = '~';
update master_data set description = 'WHITE SUMMIT WHITE METALLIC GOLD' where data_type = 'DIFF_C' and data_code = '17073' and parent_code = '~';
update master_data set description = 'WHITE TEAM RED MUSLIN MTLC GOLD STAR' where data_type = 'DIFF_C' and data_code = '17225' and parent_code = '~';
update master_data set description = 'WHITE OFFWHITE CREAM WHITE' where data_type = 'DIFF_C' and data_code = '17271' and parent_code = '~';
update master_data set description = 'WHITE OIL GREEN SAIL VOLT' where data_type = 'DIFF_C' and data_code = '17426' and parent_code = '~';
update master_data set description = 'WHITE WHITE SAIL BLACK CANVAS' where data_type = 'DIFF_C' and data_code = '17443' and parent_code = '~';
update master_data set description = 'COCONUT MILK SANDDRIFT FOOTBALL GREY' where data_type = 'DIFF_C' and data_code = '17456' and parent_code = '~';
update master_data set description = 'WHITE ROUGH GREEN SUMMIT WHITE GUM BROWN' where data_type = 'DIFF_C' and data_code = '17457' and parent_code = '~';
update master_data set description = 'OFF WHITE CLEAR PINK OFF WHITE' where data_type = 'DIFF_C' and data_code = '17501' and parent_code = '~';
update master_data set description = 'WHITE BIRKO' where data_type = 'DIFF_C' and data_code = '17532' and parent_code = '~';
update master_data set description = 'ALLIGATOR UTILITY WHITE' where data_type = 'DIFF_C' and data_code = '17548' and parent_code = '~';
update master_data set description = 'ANTIQUE WHITE SUEDE' where data_type = 'DIFF_C' and data_code = '17665' and parent_code = '~';
update master_data set description = 'CACAO WOW SAIL COCONUT MILK BLACK' where data_type = 'DIFF_C' and data_code = '17833' and parent_code = '~';
update master_data set description = 'SUEDE ANTIQUE WHITE' where data_type = 'DIFF_C' and data_code = '18161' and parent_code = '~';
update master_data set description = 'CHARCOAL SUEDE' where data_type = 'DIFF_C' and data_code = '20437' and parent_code = '~';
update master_data set description = 'TAUPE' where data_type = 'DIFF_C' and data_code = '20674' and parent_code = '~';
update master_data set description = 'GREY WHITE' where data_type = 'DIFF_C' and data_code = '21716' and parent_code = '~';
update master_data set description = 'PURE PLATINUM WHITE' where data_type = 'DIFF_C' and data_code = '22939' and parent_code = '~';
update master_data set description = 'STONE COIN' where data_type = 'DIFF_C' and data_code = '24574' and parent_code = '~';
update master_data set description = 'SUEDE LIGHT SMOKE GREY WHITE SMOKE GREY BLACK' where data_type = 'DIFF_C' and data_code = '24617' and parent_code = '~';
update master_data set description = 'DESERT DUST GREY TAUPE' where data_type = 'DIFF_C' and data_code = '25182' and parent_code = '~';
update master_data set description = 'VELVET GREY SFB' where data_type = 'DIFF_C' and data_code = '25265' and parent_code = '~';
update master_data set description = 'STONE COIN EVA' where data_type = 'DIFF_C' and data_code = '25552' and parent_code = '~';
update master_data set description = 'VELVET GREY BIRKO' where data_type = 'DIFF_C' and data_code = '25709' and parent_code = '~';
update master_data set description = 'OILED IRON' where data_type = 'DIFF_C' and data_code = '25734' and parent_code = '~';
update master_data set description = 'CONCRETE GRAY' where data_type = 'DIFF_C' and data_code = '25735' and parent_code = '~';
update master_data set description = 'SUEDE VELVET GREY' where data_type = 'DIFF_C' and data_code = '25843' and parent_code = '~';
update master_data set description = 'CONCRETE GRAY CONTRAST' where data_type = 'DIFF_C' and data_code = '25844' and parent_code = '~';
update master_data set description = 'DESERT BUCK WHALE GRAY' where data_type = 'DIFF_C' and data_code = '25848' and parent_code = '~';
update master_data set description = 'BASALT GREY TFB' where data_type = 'DIFF_C' and data_code = '25868' and parent_code = '~';
update master_data set description = 'GRAY TAUPE EVA' where data_type = 'DIFF_C' and data_code = '25869' and parent_code = '~';
update master_data set description = 'BARELY GREY EGRET BLACK' where data_type = 'DIFF_C' and data_code = '25915' and parent_code = '~';
update master_data set description = 'BASALT GREY EVA' where data_type = 'DIFF_C' and data_code = '26075' and parent_code = '~';
update master_data set description = 'VELVET GREY BFBC' where data_type = 'DIFF_C' and data_code = '26077' and parent_code = '~';
update master_data set description = 'GREY TAUPE BFBC' where data_type = 'DIFF_C' and data_code = '26078' and parent_code = '~';
update master_data set description = 'NEW NAVY' where data_type = 'DIFF_C' and data_code = '30324' and parent_code = '~';
update master_data set description = 'BLUE LEATHER' where data_type = 'DIFF_C' and data_code = '30451' and parent_code = '~';
update master_data set description = 'DUSTY BLUE' where data_type = 'DIFF_C' and data_code = '31554' and parent_code = '~';
update master_data set description = 'NAVY WHITE' where data_type = 'DIFF_C' and data_code = '32063' and parent_code = '~';
update master_data set description = 'BLUE BIRKO FLOR' where data_type = 'DIFF_C' and data_code = '33581' and parent_code = '~';
update master_data set description = 'BLUE WHITE GUM' where data_type = 'DIFF_C' and data_code = '34418' and parent_code = '~';
update master_data set description = 'COLLEGIATE NAVY WHITE' where data_type = 'DIFF_C' and data_code = '34504' and parent_code = '~';
update master_data set description = 'ACTIVE NAVY EVA' where data_type = 'DIFF_C' and data_code = '35419' and parent_code = '~';
update master_data set description = 'BLUE WHITE WHITE' where data_type = 'DIFF_C' and data_code = '35431' and parent_code = '~';
update master_data set description = 'ULTRA BLUE EVA' where data_type = 'DIFF_C' and data_code = '35564' and parent_code = '~';
update master_data set description = 'BLUE TINT WHITE' where data_type = 'DIFF_C' and data_code = '35566' and parent_code = '~';
update master_data set description = 'LIGHT BLUE GREEN' where data_type = 'DIFF_C' and data_code = '35698' and parent_code = '~';
update master_data set description = 'SKY BLUE EVA' where data_type = 'DIFF_C' and data_code = '35780' and parent_code = '~';
update master_data set description = 'DESERT DUST INDIGO BLUE' where data_type = 'DIFF_C' and data_code = '35783' and parent_code = '~';
update master_data set description = 'ADER IMPERIAL BLUE WHITE BLACK' where data_type = 'DIFF_C' and data_code = '35805' and parent_code = '~';
update master_data set description = 'SEMI BLUE BURST WHITE SEMI GREEN SPARK' where data_type = 'DIFF_C' and data_code = '35899' and parent_code = '~';
update master_data set description = 'ELEMENTAL BLUE' where data_type = 'DIFF_C' and data_code = '35902' and parent_code = '~';
update master_data set description = 'ANCESTRAL BLUE EGRET BLACK' where data_type = 'DIFF_C' and data_code = '35904' and parent_code = '~';
update master_data set description = 'ELEMENTAL BLUE EVA' where data_type = 'DIFF_C' and data_code = '35922' and parent_code = '~';
update master_data set description = 'BLUEBERRY ICE' where data_type = 'DIFF_C' and data_code = '36125' and parent_code = '~';
update master_data set description = 'YELLOW WHITE' where data_type = 'DIFF_C' and data_code = '40555' and parent_code = '~';
update master_data set description = 'SAIL SAIL LEMON TWIST BLACK LEOPARD' where data_type = 'DIFF_C' and data_code = '40861' and parent_code = '~';
update master_data set description = 'SESAME YELLOW OCHRE SAIL OFF NOIR CINNABAR WHITE' where data_type = 'DIFF_C' and data_code = '40896' and parent_code = '~';
update master_data set description = 'POPCORN EVA' where data_type = 'DIFF_C' and data_code = '40915' and parent_code = '~';
update master_data set description = 'BRUCE LEE YELLOW BLACK' where data_type = 'DIFF_C' and data_code = '40996' and parent_code = '~';
update master_data set description = 'AWAKE TAN' where data_type = 'DIFF_C' and data_code = '46200' and parent_code = '~';
update master_data set description = 'DESERT BUCK ROAST' where data_type = 'DIFF_C' and data_code = '46202' and parent_code = '~';
update master_data set description = 'BROWN' where data_type = 'DIFF_C' and data_code = '50000' and parent_code = '~';
update master_data set description = 'DARK BROWN LEATHER' where data_type = 'DIFF_C' and data_code = '51323' and parent_code = '~';
update master_data set description = 'MOCCA' where data_type = 'DIFF_C' and data_code = '51875' and parent_code = '~';
update master_data set description = 'MINK' where data_type = 'DIFF_C' and data_code = '52302' and parent_code = '~';
update master_data set description = 'MOCCA SUEDE' where data_type = 'DIFF_C' and data_code = '52303' and parent_code = '~';
update master_data set description = 'GINGER BROWN' where data_type = 'DIFF_C' and data_code = '52591' and parent_code = '~';
update master_data set description = 'LT OREWOOD BROWN WHITE' where data_type = 'DIFF_C' and data_code = '52652' and parent_code = '~';
update master_data set description = 'CHALKY BROWN OFF WHTE BRANCH' where data_type = 'DIFF_C' and data_code = '52705' and parent_code = '~';
update master_data set description = 'CORK BROWN' where data_type = 'DIFF_C' and data_code = '52778' and parent_code = '~';
update master_data set description = 'DESERT SOIL GEO CAMO' where data_type = 'DIFF_C' and data_code = '52864' and parent_code = '~';
update master_data set description = 'HABANA WAXY LEATHER' where data_type = 'DIFF_C' and data_code = '52865' and parent_code = '~';
update master_data set description = 'BF DARK BROWN' where data_type = 'DIFF_C' and data_code = '52866' and parent_code = '~';
update master_data set description = 'BROWN RENEW' where data_type = 'DIFF_C' and data_code = '52872' and parent_code = '~';
update master_data set description = 'SAIL VELVET BROWN ATMOSPHEREBROWN' where data_type = 'DIFF_C' and data_code = '52895' and parent_code = '~';
update master_data set description = 'ROAST EVA' where data_type = 'DIFF_C' and data_code = '52966' and parent_code = '~';
update master_data set description = 'TOBACCO BROWN OILED LEATHER' where data_type = 'DIFF_C' and data_code = '52967' and parent_code = '~';
update master_data set description = 'SUEDE MOCCA' where data_type = 'DIFF_C' and data_code = '52968' and parent_code = '~';
update master_data set description = 'VINTAGE WOOD ROAST' where data_type = 'DIFF_C' and data_code = '52969' and parent_code = '~';
update master_data set description = 'EGRET BROWN GOLD' where data_type = 'DIFF_C' and data_code = '52972' and parent_code = '~';
update master_data set description = 'OILED COGNAC' where data_type = 'DIFF_C' and data_code = '53180' and parent_code = '~';
update master_data set description = 'CARAFE TFB' where data_type = 'DIFF_C' and data_code = '53531' and parent_code = '~';
update master_data set description = 'BLACK OILED LEATHER SFB' where data_type = 'DIFF_C' and data_code = '58037' and parent_code = '~';
update master_data set description = 'VERNAL POOL EGRET BLACK' where data_type = 'DIFF_C' and data_code = '58156' and parent_code = '~';
update master_data set description = 'DARK TEA TFB' where data_type = 'DIFF_C' and data_code = '58337' and parent_code = '~';
update master_data set description = 'DARK TEA MIX' where data_type = 'DIFF_C' and data_code = '58342' and parent_code = '~';
update master_data set description = 'ACTIVE RED EVA' where data_type = 'DIFF_C' and data_code = '63211' and parent_code = '~';
update master_data set description = 'ORANGE WHITE WHITE' where data_type = 'DIFF_C' and data_code = '63216' and parent_code = '~';
update master_data set description = 'ORANGE GREEN  GUM' where data_type = 'DIFF_C' and data_code = '63247' and parent_code = '~';
update master_data set description = 'PAPAYA' where data_type = 'DIFF_C' and data_code = '63362' and parent_code = '~';
update master_data set description = 'SANDDRIFT ARCTIC ORANGE LIGHT SOFT PINK NEXT NATUR' where data_type = 'DIFF_C' and data_code = '63397' and parent_code = '~';
update master_data set description = 'CORAL EGRET BLACK' where data_type = 'DIFF_C' and data_code = '63468' and parent_code = '~';
update master_data set description = 'ORANGE GUM HONEY BLUE FLAME' where data_type = 'DIFF_C' and data_code = '63555' and parent_code = '~';
update master_data set description = 'ORANGE SOLAR GREEN GUM' where data_type = 'DIFF_C' and data_code = '63586' and parent_code = '~';
update master_data set description = 'RED PURPLE BURST GUM' where data_type = 'DIFF_C' and data_code = '63610' and parent_code = '~';
update master_data set description = 'BLUEBIRD SOLAR ORANGE GUM' where data_type = 'DIFF_C' and data_code = '63611' and parent_code = '~';
update master_data set description = 'LIGHT JELLYFISH JITTER RED EGRET' where data_type = 'DIFF_C' and data_code = '63654' and parent_code = '~';
update master_data set description = 'RED BLACK SKETCH' where data_type = 'DIFF_C' and data_code = '63658' and parent_code = '~';
update master_data set description = 'TS MED OLIVE INFRARED BLACK SAIL' where data_type = 'DIFF_C' and data_code = '67293' and parent_code = '~';
update master_data set description = 'MED OLIVE INFRARED TS' where data_type = 'DIFF_C' and data_code = '67326' and parent_code = '~';
update master_data set description = 'FADED KHAKI' where data_type = 'DIFF_C' and data_code = '67461' and parent_code = '~';
update master_data set description = 'ACTIVE KHAKI EVA' where data_type = 'DIFF_C' and data_code = '67462' and parent_code = '~';
update master_data set description = 'COOL SAGE SLATE' where data_type = 'DIFF_C' and data_code = '67496' and parent_code = '~';
update master_data set description = 'AWAKE GREEN' where data_type = 'DIFF_C' and data_code = '67611' and parent_code = '~';
update master_data set description = 'DESERT BUCK FADED KHAKI' where data_type = 'DIFF_C' and data_code = '67620' and parent_code = '~';
update master_data set description = 'GREEN OXIDE OFF WHITE SHADOW GREEN' where data_type = 'DIFF_C' and data_code = '67688' and parent_code = '~';
update master_data set description = 'SUMMIT SAGE EGRET BLACK' where data_type = 'DIFF_C' and data_code = '67787' and parent_code = '~';
update master_data set description = 'PULSE MINT OFF WHITE PULSE MINT' where data_type = 'DIFF_C' and data_code = '67827' and parent_code = '~';
update master_data set description = 'DESERT DUST THYME' where data_type = 'DIFF_C' and data_code = '67854' and parent_code = '~';
update master_data set description = 'ACW RIFLE GREEN SILVER BIRCH' where data_type = 'DIFF_C' and data_code = '67868' and parent_code = '~';
update master_data set description = 'MEDIUM OLIVE SAIL COCONUT MILK BLACK' where data_type = 'DIFF_C' and data_code = '67889' and parent_code = '~';
update master_data set description = 'SEMI GREEN SPARK WHITE SEMI GREEN SPARK' where data_type = 'DIFF_C' and data_code = '67933' and parent_code = '~';
update master_data set description = 'VINTAGE CARGO EGRET BLACK' where data_type = 'DIFF_C' and data_code = '67946' and parent_code = '~';
update master_data set description = 'PRISM GREEN CHAOS FUCHSIA EGRET' where data_type = 'DIFF_C' and data_code = '67958' and parent_code = '~';
update master_data set description = 'FADED KHAKI OILED LEATHER' where data_type = 'DIFF_C' and data_code = '67967' and parent_code = '~';
update master_data set description = 'BF FADED KHAKI' where data_type = 'DIFF_C' and data_code = '67985' and parent_code = '~';
update master_data set description = 'FADED KHAKI SUEDE' where data_type = 'DIFF_C' and data_code = '68117' and parent_code = '~';
update master_data set description = 'FADED KHAKI OILED LEATHER N' where data_type = 'DIFF_C' and data_code = '68126' and parent_code = '~';
update master_data set description = 'PURE SAGE' where data_type = 'DIFF_C' and data_code = '68221' and parent_code = '~';
update master_data set description = 'PURE SAGE EVA' where data_type = 'DIFF_C' and data_code = '68228' and parent_code = '~';
update master_data set description = 'THYME SMOOTH LEATHER' where data_type = 'DIFF_C' and data_code = '68292' and parent_code = '~';
update master_data set description = 'THYME AGAIN EGRET BLACK' where data_type = 'DIFF_C' and data_code = '68422' and parent_code = '~';
update master_data set description = 'PINK WHITE' where data_type = 'DIFF_C' and data_code = '76371' and parent_code = '~';
update master_data set description = 'PINK WHITE PINK' where data_type = 'DIFF_C' and data_code = '77079' and parent_code = '~';
update master_data set description = 'PINK FOAM PINK FOAM' where data_type = 'DIFF_C' and data_code = '77157' and parent_code = '~';
update master_data set description = 'SUMMIT WHITE LIGHT MADDER ROOT' where data_type = 'DIFF_C' and data_code = '77369' and parent_code = '~';
update master_data set description = 'GOLF WANG PINK DOGWOOD VINTAGE WHITE' where data_type = 'DIFF_C' and data_code = '77421' and parent_code = '~';
update master_data set description = 'LIGHT PINK YELLOW' where data_type = 'DIFF_C' and data_code = '77528' and parent_code = '~';
update master_data set description = 'DUSTY PINK GREEN' where data_type = 'DIFF_C' and data_code = '77529' and parent_code = '~';
update master_data set description = 'BEIGE PINK LIGHT BLUE' where data_type = 'DIFF_C' and data_code = '77530' and parent_code = '~';
update master_data set description = 'AMBER PINK MIDNIGHT NAVY EGRET' where data_type = 'DIFF_C' and data_code = '77657' and parent_code = '~';
update master_data set description = 'OOPS PINK GUM HONEY ORGANE' where data_type = 'DIFF_C' and data_code = '77670' and parent_code = '~';
update master_data set description = 'BLISS PINK SEMI FLASH AQUA GUM' where data_type = 'DIFF_C' and data_code = '77698' and parent_code = '~';
update master_data set description = 'PURPLE ORANGE GUM' where data_type = 'DIFF_C' and data_code = '81009' and parent_code = '~';
update master_data set description = 'AWAKE PURPLE' where data_type = 'DIFF_C' and data_code = '81041' and parent_code = '~';
update master_data set description = 'STARTDUST LILAC EGRET BLACK' where data_type = 'DIFF_C' and data_code = '81157' and parent_code = '~';
update master_data set description = 'NIGHT INDIGO SOLAR YELLOW GOLD METALIC' where data_type = 'DIFF_C' and data_code = '81207' and parent_code = '~';
update master_data set description = 'DARK BEETROOT' where data_type = 'DIFF_C' and data_code = '81214' and parent_code = '~';
update master_data set description = 'TAUPE SUEDE' where data_type = 'DIFF_C' and data_code = '85216' and parent_code = '~';
update master_data set description = 'STONE' where data_type = 'DIFF_C' and data_code = '85358' and parent_code = '~';
update master_data set description = 'PARCHMENT' where data_type = 'DIFF_C' and data_code = '86168' and parent_code = '~';
update master_data set description = 'DRIFTWOOD LIGHT FAWN BLACK' where data_type = 'DIFF_C' and data_code = '87146' and parent_code = '~';
update master_data set description = 'OS COMM NATURAL IVORY EGRET' where data_type = 'DIFF_C' and data_code = '87375' and parent_code = '~';
update master_data set description = 'BOLD JADE' where data_type = 'DIFF_C' and data_code = '87486' and parent_code = '~';
update master_data set description = 'SAIL LIGHT BONE SAIL BLACK' where data_type = 'DIFF_C' and data_code = '87777' and parent_code = '~';
update master_data set description = 'SAIL DOLL WHEAT GRASS LIGHT BONE' where data_type = 'DIFF_C' and data_code = '87780' and parent_code = '~';
update master_data set description = 'ORCHID FUSION WHITE ORCHID FUSION' where data_type = 'DIFF_C' and data_code = '88413' and parent_code = '~';
update master_data set description = 'STONE COIN BF' where data_type = 'DIFF_C' and data_code = '88464' and parent_code = '~';
update master_data set description = 'THYME SUEDE OILED LEATHER' where data_type = 'DIFF_C' and data_code = '88658' and parent_code = '~';
update master_data set description = 'EGGSHELL EVA' where data_type = 'DIFF_C' and data_code = '88773' and parent_code = '~';
update master_data set description = 'OYSTER SUEDE' where data_type = 'DIFF_C' and data_code = '89384' and parent_code = '~';
update master_data set description = 'SEQUOIA LIGHT ARMY LIGHT SILVER' where data_type = 'DIFF_C' and data_code = '96560' and parent_code = '~';
update master_data set description = '2.5' where data_type = 'DIFF_S' and data_code = '025' and parent_code = '~';
update master_data set description = '3' where data_type = 'DIFF_S' and data_code = '030' and parent_code = '~';
update master_data set description = '3.5' where data_type = 'DIFF_S' and data_code = '035' and parent_code = '~';
update master_data set description = '4' where data_type = 'DIFF_S' and data_code = '040' and parent_code = '~';
update master_data set description = '4.5' where data_type = 'DIFF_S' and data_code = '045' and parent_code = '~';
update master_data set description = '5' where data_type = 'DIFF_S' and data_code = '050' and parent_code = '~';
update master_data set description = '5.5' where data_type = 'DIFF_S' and data_code = '055' and parent_code = '~';
update master_data set description = '6' where data_type = 'DIFF_S' and data_code = '060' and parent_code = '~';
update master_data set description = '6.5' where data_type = 'DIFF_S' and data_code = '065' and parent_code = '~';
update master_data set description = '7' where data_type = 'DIFF_S' and data_code = '070' and parent_code = '~';
update master_data set description = '7.5' where data_type = 'DIFF_S' and data_code = '075' and parent_code = '~';
update master_data set description = '8' where data_type = 'DIFF_S' and data_code = '080' and parent_code = '~';
update master_data set description = '8.5' where data_type = 'DIFF_S' and data_code = '085' and parent_code = '~';
update master_data set description = '9' where data_type = 'DIFF_S' and data_code = '090' and parent_code = '~';
update master_data set description = '9.5' where data_type = 'DIFF_S' and data_code = '095' and parent_code = '~';
update master_data set description = '10' where data_type = 'DIFF_S' and data_code = '100' and parent_code = '~';
update master_data set description = '10.5' where data_type = 'DIFF_S' and data_code = '105' and parent_code = '~';
update master_data set description = '11' where data_type = 'DIFF_S' and data_code = '110' and parent_code = '~';
update master_data set description = '11.5' where data_type = 'DIFF_S' and data_code = '115' and parent_code = '~';
update master_data set description = '12' where data_type = 'DIFF_S' and data_code = '120' and parent_code = '~';
update master_data set description = '12.5' where data_type = 'DIFF_S' and data_code = '125' and parent_code = '~';
update master_data set description = '13' where data_type = 'DIFF_S' and data_code = '130' and parent_code = '~';
update master_data set description = '14' where data_type = 'DIFF_S' and data_code = '140' and parent_code = '~';
update master_data set description = '15' where data_type = 'DIFF_S' and data_code = '150' and parent_code = '~';
update master_data set description = 'S' where data_type = 'DIFF_S' and data_code = '992' and parent_code = '~';
update master_data set description = 'M' where data_type = 'DIFF_S' and data_code = '993' and parent_code = '~';
update master_data set description = 'L' where data_type = 'DIFF_S' and data_code = '994' and parent_code = '~';
update master_data set description = 'XL' where data_type = 'DIFF_S' and data_code = '995' and parent_code = '~';
update master_data set description = 'XXL' where data_type = 'DIFF_S' and data_code = '996' and parent_code = '~';

commit;

select data_type, count(*) with_description from master_data
 where data_type in ('DIFF_C','DIFF_S') and description is not null
 group by data_type order by 1;
