import type { IntegrationPayload } from '../models/integrationPayload'
import {
  operationNeedsExistingOrder,
  operationNeedsExistingSkus,
  operationNeedsExistingStyle,
  type OfficeRequest,
  type UserReference,
} from '../models/officeRequest'

export function mapRequestToPayload(request: OfficeRequest, actor: UserReference, now = new Date()): IntegrationPayload {
  if (!request.actionRequestId) throw new Error('ACTION_REQUEST_ID must be assigned before payload mapping')
  return {
    OPERATION_NAME: request.operationName,
    ACTION_REQUEST_ID: request.actionRequestId,
    SOURCE_SYSTEM: 'OFFICE_ORDERING',
    SOURCE_STYLE_REF: request.sourceStyleRef,
    SOURCE_ORDER_REF: request.sourceOrderRef,
    SOURCE_VERSION: String(request.sourceVersion),
    USER_ID: actor.id,
    DATE_TIME_STAMP: now.toISOString(),
    STYLE: operationNeedsExistingStyle(request.operationName) ? request.style.existingStyle : null,
    ORDER_NO: operationNeedsExistingOrder(request.operationName) ? request.order.existingOrderNo : null,
    DEPARTMENT: request.style.department,
    CLASS: request.style.classNumber,
    SUBCLASS: request.style.subclass,
    COLOUR_GROUP: request.style.colourGroup,
    COLOUR: request.style.colour,
    SIZE_GROUP: request.style.sizeGroup,
    WIDTH_GROUP: request.style.widthGroup || null,
    PACK_IND: 'N',
    STYLE_DESC: request.style.description,
    STYLE_SHORT_DESC: request.style.shortDescription,
    SUPPLIER: request.sourcing.supplier,
    VPN: request.sourcing.vpn,
    ORIGIN_COUNTRY: request.sourcing.originCountry,
    MANUFACTURE_CTRY: request.sourcing.manufacturingCountry,
    CURRENCY_CODE: request.sourcing.currencyCode || 'USD',
    COST_PRICE: request.sourcing.costPrice,
    UNIT_COST: request.sourcing.costPrice,
    NON_MERCH_COST: request.sourcing.nonMerchCost,
    UPDATE_COST_IND: 'Y',
    PACK_SIZE_CASE: request.sourcing.casePackSize,
    PACK_SIZE_INNER: request.sourcing.innerPackSize,
    RSP: request.sourcing.rsp,
    RETAIL_PRICE: request.sourcing.rsp,
    UPDATE_RSP_IND: 'Y',
    SEASON: request.style.season,
    PHASE: request.style.phase,
    PLMSizeCurveDtl: request.variants.map((variant) => ({
      SOURCE_VARIANT_REF: variant.sourceVariantRef,
      SKU_SIZE: variant.size,
      SKU_WIDTH: variant.width || null,
      SKU_QTY: variant.quantity,
      SKU_ID: operationNeedsExistingSkus(request.operationName) ? variant.skuId : null,
    })),
    PLMPacklotDtl: null,
    PLMStyleUDADtl: [],
    NOT_BEFORE_DATE: request.order.notBeforeDate,
    NOT_AFTER_DATE: request.order.notAfterDate,
    OTB_EOW_DATE: request.order.otbEowDate,
    EARLIEST_SHIP_DATE: request.order.earliestShipDate,
    LATEST_SHIP_DATE: request.order.latestShipDate,
    DELIVERY_LOC: request.order.deliveryLocation,
    PO_TYPE: request.order.poType,
    ORDER_EXCHANGE_RATE: request.order.exchangeRate,
    VALLEY_PERIOD_IND: 'N',
    ON_HANGER: 'N',
    FIRST_PASS: 'N',
    TICKETS_REQUIRED: 'N',
    PDF_PO_STATUS: 'N',
    SPECIAL_INSTRUCTION: request.order.specialInstructions || null,
    DUTY_CODE: request.order.dutyCode,
    DUTY_RATE: request.order.dutyRate,
  }
}
